version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mongo:4.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - deps-{{ .Branch }}-
            - deps-
      - run:
          name: Install Tools
          command: |
            wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | sudo apt-key add -
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            sudo apt-get update
            sudo apt-get install -y --force-yes mongodb-org-shell libssl-dev
      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 10s
      - run:
          name: Setup database
          command: |
            mongo test-service-database --eval 'db.createUser({user:"snake.eyes",pwd:"123456",roles:["readWrite"], passwordDigestor: "server"});'
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go mod download
      - run: make coverage-ci
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: test-results
